### PR TITLE
here are the finalpage-finalview files 

### PR DESCRIPTION
**Pull request by alqayadhi**
Closes https://github.com/arkaitzgarro/browser-quiz-project-starter/issues/8

### CODE REVIEW

**Comment by alqayadhi** [comment]
Okay then 👍 
so what next :)

**Review by arkaitzgarro — APPROVED** [review]

**Comment by arkaitzgarro** [comment]
> Okay then 👍 so what next :)

I created another issue to show the final page when the user answers all the questions: https://github.com/arkaitzgarro/browser-quiz-project-starter/issues/19

Can you maybe work on this one?

**Comment by alqayadhi** [comment]
I think this demand is similar to the file I have uploaded finalView.js

**Comment by arkaitzgarro** [comment]
> I think this demand is similar to the file I have uploaded finalView.js

Yes, the page is created, but it's never shown. When the user answers the last question, we need to show the final page, and this is not the case right now.

**Pull request merged**
