### PR TITLE
Green button in set timeout

### PR DESCRIPTION
**Pull request by anutka2610**

### CODE REVIEW

**Comment by arkaitzgarro** [comment]
@anutka2610 there's a lot in this PR that doesn't belong to it, it's removing and adding code, and it shouldn't. Can you start over from the latest `main`?

**Comment by anutka2610** [comment]
when I'm on main branch, and i did pull, when i want git status I had this : 
git status
On branch main
Your branch is ahead of 'origin/main' by 7 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

**Comment by anutka2610** [comment]
I need to push from main branch? 
So this is my problem

**Comment by arkaitzgarro** [comment]
Implemented in #52

**Pull request closed without merging**
